# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: RELEASE-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  tags:
    include:
      - v*
pr: none

variables:
  DOCKERHUBID: 'nekia'

jobs:
- job: Release
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DownloadSecureFile@1
    name: mySecureFile
    inputs:
      secureFile: 'passwd.txt'
  - script: 'cat $(mySecureFile.secureFilePath) | docker login --username $(DOCKERHUBID) --password-stdin'
    displayName: Login to Docker
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
      ./build_docker_image_rpi3.sh
    displayName: Build Docker Images for arm64v8
  - script: docker tag hyperledger/explorer $(DOCKERHUBID)/explorer:$(git describe --abbrev=0 --tags | cut -d 'v' -f 2)
    displayName: Tag Explorer Image
  - script: docker tag hyperledger/explorer-db $(DOCKERHUBID)/explorer-db:$(git describe --abbrev=0 --tags | cut -d 'v' -f 2)
    displayName: Tag Explorer DB Image
  - script: docker push $(DOCKERHUBID)/explorer
    displayName: Push Explorer Latest Image
  - script: docker push $(DOCKERHUBID)/explorer-db
    displayName: Push Explorer DB Latest Image
  - script: docker push $(DOCKERHUBID)/explorer:$(git describe --abbrev=0 --tags | cut -d 'v' -f 2)
    displayName: Push Explorer Versioned Image
  - script: docker push $(DOCKERHUBID)/explorer-db:$(git describe --abbrev=0 --tags | cut -d 'v' -f 2)
    displayName: Push Explorer DB Versioned Image