
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata_explorer:
  pgdata_refiner:
  walletstore:

networks:
  mynetwork.com:
    external:
      name: fabric_test
  explorer-internal:

services:

  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.mynetwork.com
    hostname: explorerdb.mynetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata_explorer:/var/lib/postgresql/data
    networks:
      - explorer-internal

  explorer.mynetwork.com:
    image: hyperledger/explorer:latest
    container_name: explorer.mynetwork.com
    hostname: explorer.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.mynetwork.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./examples/net1/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./examples/net1/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - /home/atsushi/dev/hyperledger/fabric-samples/test-network/organizations:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.mynetwork.com:
        condition: service_healthy
    networks:
      - mynetwork.com
      - explorer-internal

  refinerdb.mynetwork.com:
    image: fujitsu/refinerdb:latest
    container_name: refinerdb
    hostname: refinerdb.mynetwork.com
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata_refiner:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - mynetwork.com

  refiner.mynetwork.com:
    image: fujitsu/refiner:latest
    container_name: refiner
    hostname: refiner.mynetwork.com
    volumes:
      - /home/atsushi/dev/hyperledger/Ledger-Data-Refiner/config/config.ini:/opt/config/config.ini
      - /home/atsushi/dev/hyperledger/Ledger-Data-Refiner/config/connection-config-docker.yaml:/opt/config/connection-config.yaml
      - /home/atsushi/dev/hyperledger/Ledger-Data-Refiner/log:/root/refiner/log
      - /home/atsushi/dev/hyperledger/fabric-samples/test-network/organizations:/opt/organizations
    command: sh -c "/opt/ledgerdata-refiner"
    ports:
      - 30052:30052
    depends_on:
      refinerdb.mynetwork.com:
        condition: service_healthy
    networks:
      - mynetwork.com
