# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, github-action ]
  pull_request:
    branches: [ main, github-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    # - run: npm config set prefix ~/npm
    - run: yarn install
    - run: yarn run test
    - name: Test client codebase
      run: |
        cd ./client && yarn install
        yarn run test:ci -- -u --coverage
    - name: Create Cobertura Report
      run: |
        cd client
        wget https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py
        python lcov_cobertura.py ./coverage/lcov.info
    - name: cobertura-report
      uses: 5monkeys/cobertura-action@v8
      with:
        # The GITHUB_TOKEN for this repo
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Path to the cobertura file.
        path: ./client/coverage.xml
        minimum_coverage: 75

  SanityChecks_v1_4:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      PATH: ${{ github.workspace }}/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2.1.3
      name: Setup Go environment
    - name: Get Go dependencies
      run: |
        go get -u github.com/onsi/ginkgo/ginkgo
        go get -u github.com/pkg/errors
        go get -u gopkg.in/yaml.v2
        go get -u github.com/onsi/gomega/...
        echo $PATH
        echo $GOPATH
    - uses: actions/setup-python@v2
    - run: |
        yarn install
        yarn run e2e-api-test-v1
      name: Run Sanity Checks for v1.4

  SanityChecks_v2_3:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      PATH: ${{ github.workspace }}/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2.1.3
      name: Setup Go environment
    - name: Get Go dependencies
      run: |
        go get -u github.com/onsi/ginkgo/ginkgo
        go get -u github.com/pkg/errors
        go get -u gopkg.in/yaml.v2
        go get -u github.com/onsi/gomega/...
        echo $PATH
        echo $GOPATH
    - uses: actions/setup-python@v2
    - run: |
        yarn install
        yarn run e2e-api-test-v2
      name: Run Sanity Checks for v2.3

  GUITests_v1_4:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      PATH: ${{ github.workspace }}/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2.1.3
      name: Setup Go environment
    - name: Get Go dependencies
      run: |
        go get -u github.com/onsi/ginkgo/ginkgo
        go get -u github.com/pkg/errors
        go get -u gopkg.in/yaml.v2
        go get -u github.com/onsi/gomega/...
        echo $PATH
        echo $GOPATH
    - uses: actions/setup-python@v2
    - run: |
        yarn install
        yarn run e2e-gui-test-v1
      name: Run GUI Tests for v1.4

  GUITests_v2_3:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      PATH: ${{ github.workspace }}/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v2.1.3
      name: Setup Go environment
    - name: Get Go dependencies
      run: |
        go get -u github.com/onsi/ginkgo/ginkgo
        go get -u github.com/pkg/errors
        go get -u gopkg.in/yaml.v2
        go get -u github.com/onsi/gomega/...
        echo $PATH
        echo $GOPATH
    - uses: actions/setup-python@v2
    - run: |
        yarn install
        yarn run e2e-gui-test-v2
      name: Run GUI Tests for v2.1
